steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/v135-5247-playground-schimmer/the-cookbook', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/v135-5683-autoiam/thor-auto-iam']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'the-cookbook',
         '--image', 'gcr.io/v135-5247-playground-schimmer/the-cookbook',
         '--platform', 'managed',
         '--region', 'europe-west1',
         '--concurrency', '10',
         '--allow-unauthenticated',
         '--memory', '2Gi']
images:
- gcr.io/v135-5247-playground-schimmer/the-cookbook